<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tecnologia extends Model
{
    protected $guarded = [];
    protected $table = 'tecnologias';
//    protected $fillable =['id','nombre_tecnologia','descripcion_tecnologia'];
    

    public function practicas(){
        return $this->hasMany(Practica::class);
    }
   
//    public function getRouteKeyName()
//    {
//        return parent::getRouteKeyName('nombre_tecnologia'); // TODO: Change the autogenerated stub
//    }
}
